language: php

php:
  - 7.0
  - 7.1

before_install:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer install --no-interaction --prefer-source --dev

script:
  - phpunit --coverage-clover build/coverage/clover.xml

after_script:
  - vendor/bin/coveralls -v
